steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'gsutil'
    args: ['cp', 'gs://us.artifacts.stately-rampart-199708.appspot.com/binary/simc', './simc']
    id: binary

  # - name: gcr.io/cloud-builders/docker
  #   entrypoint: 'chmod'
  #   args: ['a+rwx', '-R', './simc']
  #   id: PermissionA
  
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args: ['-c', 'chmod 777 ./simc']
    id: PermissionB

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
      - '.'
    id: DockerBuild

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _TRIGGER_ID: 92296cad-4f47-4571-a13d-9efb6aa4e44d
  _SERVICE_NAME: cloudsimc
  _ENTRYPOINT: npm start
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _LABELS: gcb-trigger-id=92296cad-4f47-4571-a13d-9efb6aa4e44d
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - cloudsimc
